//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

== Proposal

[Basics]
====
This proposal is in the Project Proposal Phase (as defined in the http://www.eclipse.org/projects/dev_process/development_process.php[Eclipse Development Process])
and is written to declare its intent and scope. We solicit additional participation and input from the community. Please login and add your feedback in the comments
sections.

*Parent Project:*
https://projects.eclipse.org/projects/technology[Eclipse Technology]
====

=== Background:

Cloud computing has dramatically changed the infrastructure usage. Almost all companies are looking for public/private/hybrid cloud platform, and managed services.

Currently, less than 10 cloud providers are leaders on the cloud market. If some technologies are common the cloud providers, most of the managed services are specific to each provider.

We can see two main issues with the current offering:

* vendor lock-in: for cloud users, it's a real challenge to move from one cloud provider to another one. The challenge is the same while tring to move a service from a public cloud to a private one.
* service lock-out: for service providers, it's almost impossible to have a native service integration in the cloud provider catalog. It means that, the best service provider can do, is to provide the best integration possible for one specific cloud provider.

We think about the value of have a standard allowing native service integration on any cloud provider, and smooth integration/use of any cloud provider.

We strongly believe in a more open cloud ecosystem, based on standard. Eclipse OSC aims to be this standard for native services implementation.

Any cloud and service provider can implement Eclipse OSC, expanding the ecosystem and providing value for cloud users.

=== Scope:

Eclipse Open Services Cloud provides a standard to implement cloud native services.

Eclipse Open Services Cloud provides:

. standard API with schema and data binding to implement native services, including existing services and services catalog.
. TCK (Technology Compatibility Kit) to validate an implementation is fully compliant with the API
. a very simple implementation of OSC API illustrating the API usage (both implementation and API client)

=== Description:



=== Why Here?:

OSC target is to provide a standard, quite similar to Jakarta EE. We think that Eclipse can take ownership of cloud related standards.

It's also probable OSC use Eclipse technologies, at least for the simple implementation, as Eclipse Jetty or Eclipse Paho.

=== Licenses:

http://www.apache.org/licenses/LICENSE-2.0[Apache License 2.0]

=== Project Scheduling:

* Initial Release - Q4 FY 21 - release of current API with new OSS branding and licensing as well as release of documentation reworked with OSS branding
* Release 0.2 - Q1 FY 22 - first API GA, building community, advertising
* Release 0.3 - Q2 FY 22 - reference implementation and GA
* Release 0.4 - Q3 FY 22 - seeking new implementation (adoption phase)

=== Future Work:

[People]
====
*Project Leads:*
JB Onofré

*Committers:*

*Mentors:*

*Interested Parties:*
A number of existing cloud and service providers have expressed interest in OSC standard:
* Huawei
* OVH Cloud (?)
* Microsoft Azure (?)
====

[Source Code]
====
*Initial Contribution:*
We will be contributing the following code as part of the initial contribution of this project:

. OSC API - the base of the standard API including schema and data binding
. OSC TCK - the TCK (Technology Compatibility Kit) to validate API compliance for OSC implementation
. OSC Simple - a very simple implementation of OSC API (local runtime)

* Source Repository Type:*
http://github.com/jbonofre/osc[Git]
====

