= Eclipse OpenServicesCloud

Eclipse OpenServicesCloud is framework providing a set of common API implemented by any OSC cloud provider.

The purpose of this framework is to provide a standardized and common access layer to the cloud services engines.

== Why?

As OSC is an open source effort and a common layer, there's no lock-in on the clud engines. It facilitates and standardizes access to the cloud engines, allowing users to create multi-cloud services, whatever the services are running on public, private, or hybrid cloud platforms.

On the other hand, there's no lock-out, meaning that any ecosystem can easily create managed cloud services without being coupled to a single cloud engine.

== APIs

Eclipse OSC provides the following APIs:

* identity to deal with cloud engine access, users, groups, roles management
* computing machine abstract the access to virtual machines
* ...

Most of the API uses a JSON (JSON schema) data binding.

NB: OSC doesn't cover cloud engine specific services like storages or filesystems for instance.

=== Artifacts

Each service API is provided in its own artifact. Cloud engines can pickup the APIs they want to implement by providing API artifacts as implementation dependencies.

For instance:

[code,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>mycloudengine</groupId>
    <artifactId>myIdentityImpl</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.ocs.api</groupId>
            <artifactId>identity</artifactId>
        </dependency>
    </dependencies>

</project>
----

=== Data format

API documentation specify the data format schema, using JSON/YAML/OpenAPI.

Here's a simple example of Identity user details JSON:

[source,json]
----
{
 "user": "foo",
 "groups": [ "group1", "group2" ],
 "roles": [ "role1" ]
}
----

== TCK

The framework provides a TCK to "verify" the OSC compliance.

== Simple Reference Implementation & interesting third parties

The framework provides a very simple reference implementation, local runner, allowing you to develop and test your services on OCS.

This reference implementation is powered by Apache Karaf 5.0.0 as runtime and Apache jClouds as abstraction layer.

Here's a proposal as a possible ecosystem or interesting third parties:

* Apache Karaf (runtime/launcher)
* Apache jClouds (abstract framework on top of existing cloud engines)
* Apache Brooklyn (framework to model, deploy, manage distributed applications using declarative YAML blueprints)

== OSC compliant cloud engines

Currently the known OSC compliant cloud engines are:

* Huawei Cloud
* ...
