/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.eclipse.xpanse.modules.deployment.deployers.terraform.terraformboot.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TerraformResult
 */
@JsonPropertyOrder({
  TerraformResult.JSON_PROPERTY_COMMAND_STD_OUTPUT,
  TerraformResult.JSON_PROPERTY_COMMAND_STD_ERROR,
  TerraformResult.JSON_PROPERTY_COMMAND_SUCCESSFUL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-24T09:52:10.012096600+08:00[Asia/Shanghai]")
public class TerraformResult {
  public static final String JSON_PROPERTY_COMMAND_STD_OUTPUT = "commandStdOutput";
  private String commandStdOutput;

  public static final String JSON_PROPERTY_COMMAND_STD_ERROR = "commandStdError";
  private String commandStdError;

  public static final String JSON_PROPERTY_COMMAND_SUCCESSFUL = "commandSuccessful";
  private Boolean commandSuccessful;

  public TerraformResult() {
  }

  public TerraformResult commandStdOutput(String commandStdOutput) {
    
    this.commandStdOutput = commandStdOutput;
    return this;
  }

   /**
   * Get commandStdOutput
   * @return commandStdOutput
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMAND_STD_OUTPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCommandStdOutput() {
    return commandStdOutput;
  }


  @JsonProperty(JSON_PROPERTY_COMMAND_STD_OUTPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommandStdOutput(String commandStdOutput) {
    this.commandStdOutput = commandStdOutput;
  }


  public TerraformResult commandStdError(String commandStdError) {
    
    this.commandStdError = commandStdError;
    return this;
  }

   /**
   * Get commandStdError
   * @return commandStdError
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMAND_STD_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCommandStdError() {
    return commandStdError;
  }


  @JsonProperty(JSON_PROPERTY_COMMAND_STD_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommandStdError(String commandStdError) {
    this.commandStdError = commandStdError;
  }


  public TerraformResult commandSuccessful(Boolean commandSuccessful) {
    
    this.commandSuccessful = commandSuccessful;
    return this;
  }

   /**
   * Get commandSuccessful
   * @return commandSuccessful
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMAND_SUCCESSFUL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCommandSuccessful() {
    return commandSuccessful;
  }


  @JsonProperty(JSON_PROPERTY_COMMAND_SUCCESSFUL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCommandSuccessful(Boolean commandSuccessful) {
    this.commandSuccessful = commandSuccessful;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TerraformResult terraformResult = (TerraformResult) o;
    return Objects.equals(this.commandStdOutput, terraformResult.commandStdOutput) &&
        Objects.equals(this.commandStdError, terraformResult.commandStdError) &&
        Objects.equals(this.commandSuccessful, terraformResult.commandSuccessful);
  }

  @Override
  public int hashCode() {
    return Objects.hash(commandStdOutput, commandStdError, commandSuccessful);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TerraformResult {\n");
    sb.append("    commandStdOutput: ").append(toIndentedString(commandStdOutput)).append("\n");
    sb.append("    commandStdError: ").append(toIndentedString(commandStdError)).append("\n");
    sb.append("    commandSuccessful: ").append(toIndentedString(commandSuccessful)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

