apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: managed-services.osc.eclipse.org
spec:
  group: osc.eclipse.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                ocl:
                  type: string
  scope: Namespaced
  names:
    plural: managed-services
    singular: managed-service
    kind: Osc
    shortNames:
      - ms