apiVersion: v1
kind: Service
metadata:
  name: osc
  namespace: osc
  labels:
    app: osc
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: osc