apiVersion: apps/v1
kind: Deployment
metadata:
  name: osc-demo
  labels:
    app: osc-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: osc-demo
  template:
    metadata:
      labels:
        app: osc-demo
    spec:
      containers:
        - name: osc-demo
          image: osc/osc-demo:0.1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: osc-demo
  labels:
    app: osc-demo
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: osc-demo
