/*
 * SPDX-License-Identifier: Apache-2.0
 * SPDX-FileCopyrightText: Huawei Inc.
 *
 */

package org.eclipse.xpanse.ai.generate.structure;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import lombok.Data;

/** structure of JSON response to be generated by the LLM. */
@Data
@JsonPropertyOrder({"file_name", "content"})
public class CodeGenerationResponseItem {

    @JsonProperty("file_name")
    private String fileName;

    @JsonProperty("content")
    private String content;
}
