/*
 * SPDX-License-Identifier: Apache-2.0
 * SPDX-FileCopyrightText: Huawei Inc.
 */

package org.eclipse.xpanse.modules.models.servicetemplate;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import java.util.List;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.hibernate.validator.constraints.UniqueElements;
import org.springframework.validation.annotation.Validated;

/** Defines the TerraformDeployment. */
@EqualsAndHashCode
@Data
@Validated
public class HelmDeployment {

    @Valid
    @NotNull
    @NotEmpty
    @UniqueElements
    @Schema(
            description =
                    "The input variables for the helm deployment, which will be passed to the"
                        + " deployer.The list elements must be unique. All input variables are put"
                        + " together to build a JSON 'object' with each variable as a property of"
                        + " this object.")
    private List<InputVariable> inputVariables;

    @Valid
    @NotNull
    @NotEmpty
    @UniqueElements
    @Schema(
            description =
                    "The output variables for the helm deployment, which will be generated by the"
                            + " helm deployer. The list elements must be unique.")
    private List<HelmOutputVariable> helmOutputVariables;

    @NotNull
    @Schema(description = "The kubernetes cluster for the helm deployment.")
    private KubernetesCluster kubernetesCluster;

    @NotNull
    @Schema(description = "The helm coordinates for the helm deployment.")
    private HelmCoordinates helmCoordinates;
}
