#
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Huawei Inc.
#
name: xpanse-license-check

# Run this workflow every time a new commit push to the repository
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  third-party-license-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set Up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          cp .github/workflows/.m2/settings.xml ~/.m2
      - name: Check 3rd Party Licenses
        run: mvn license-tool:license-check -Plicense-check
